/*
 * License Agreement
 *
 * Copyright (c) 2008
 * Altera Corporation, San Jose, California, USA.
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * This agreement shall be governed in all respects by the laws of the State
 * of California and by the laws of the United States of America.
 */

#ifndef __SYSTEM_H_
#define __SYSTEM_H_

/* Include definitions from linker script generator */
#include "linker.h"

#include <stdint.h>

#include "uart.h"

#define CLK_FREQ 50000000UL // 50 MHz

// TODO: Modify ?? (check the other adresses as well)
#define MEMADDR_IRQCONTROLLER ((uintptr_t)(0x00010000))

#define IRQ_UART 0

#ifndef DBUILD_VERSION
#define DBUILD_VERSION "git undefined"
#endif

#ifndef DBUILD_DATE
#define DBUILD_DATE "date undefined"
#endif

/* InterruptController

	The InterruptController serves as a simple replacement for the PLIC/CLINT.
	It provides handling for external, soft and timer interrupts.
	External interrupts are connected via Qsys and assert the IRQ_M_EXT signal to the
	core when a bit in both <pending> and <enabled> is high.
	<pending> can be read anytime and shows all current asserted interrupts,
	even if the interrupt is not enabled.
	<mtimeh_latch> is set to the current <mtimeh> value whenever <mtime> (low) is read,
	this is used to snapshot the 64-bit register and read it with 32-bit access without any changes.
	Similary mtimecmp can be written with a 64-bit value at once.
	First <mtimecmph_latch> is written with bits 63 to 32, then <mtimecmp_latch> is written
	with bit 31 to 0. Writing <mtimecmp_latch> writes directly to <mtimecmp>
	and copies the 32-bits of the high-register in the same cycle.
	While mtime is greater or equal to mtimecmp, the IRQ_M_TMR signal is asserted.
	Finally while the register <softinterupt> is holding a value equal nonzero,
	the IRQ_M_SFT signal is asserted. It takes approx. 4 instructions after the write
	until the core is interrupted.

*/

typedef volatile struct {
	uint32_t pending; // R
	uint32_t enabled; // RW
	uint32_t mtime; // RW
	uint32_t mtimeh; // RW
	uint32_t mtimeh_latch; // R
	uint32_t mtimecmp; // RW
	uint32_t mtimecmph; // RW
	uint32_t mtimecmp_latch; // W
	uint32_t mtimecmph_latch; // RW
	uint32_t softinterrupt; // RW
} InterruptController;

extern InterruptController* g_InterruptController;


/*
 * Define for each module class mastered by the CPU
 *
 */

#define __ALTERA_AVALON_JTAG_UART
#define __ALTERA_AVALON_NEW_SDRAM_CONTROLLER
#define __ALTERA_AVALON_ONCHIP_MEMORY2
#define __ALTERA_MSGDMA
#define __ALTERA_NIOS2_GEN2
#define __ALTERA_UP_AVALON_VIDEO_PIXEL_BUFFER_DMA
#define __ALTERA_UP_AVALON_VIDEO_RGB_RESAMPLER
#define __CMOS_SENSOR_INPUT
#define __I2C


/*
 * System configuration
 *
 */

#define ALT_DEVICE_FAMILY "Cyclone V"
#define ALT_ENHANCED_INTERRUPT_API_PRESENT
#define ALT_IRQ_BASE NULL
#define ALT_LOG_PORT "/dev/null"
#define ALT_LOG_PORT_BASE 0x0
#define ALT_LOG_PORT_DEV null
#define ALT_LOG_PORT_TYPE ""
#define ALT_NUM_EXTERNAL_INTERRUPT_CONTROLLERS 0
#define ALT_NUM_INTERNAL_INTERRUPT_CONTROLLERS 1
#define ALT_NUM_INTERRUPT_CONTROLLERS 1
#define ALT_STDERR "/dev/jtag_uart_0"
#define ALT_STDERR_BASE 0x8001080
#define ALT_STDERR_DEV jtag_uart_0
#define ALT_STDERR_IS_JTAG_UART
#define ALT_STDERR_PRESENT
#define ALT_STDERR_TYPE "altera_avalon_jtag_uart"
#define ALT_STDIN "/dev/jtag_uart_0"
#define ALT_STDIN_BASE 0x8001080
#define ALT_STDIN_DEV jtag_uart_0
#define ALT_STDIN_IS_JTAG_UART
#define ALT_STDIN_PRESENT
#define ALT_STDIN_TYPE "altera_avalon_jtag_uart"
#define ALT_STDOUT "/dev/jtag_uart_0"
#define ALT_STDOUT_BASE 0x8001080
#define ALT_STDOUT_DEV jtag_uart_0
#define ALT_STDOUT_IS_JTAG_UART
#define ALT_STDOUT_PRESENT
#define ALT_STDOUT_TYPE "altera_avalon_jtag_uart"
#define ALT_SYSTEM_NAME "soc_d5m_niosii_sys"


/*
 * hal configuration
 *
 */

#define ALT_INCLUDE_INSTRUCTION_RELATED_EXCEPTION_API
#define ALT_MAX_FD 32
#define ALT_SYS_CLK none
#define ALT_TIMESTAMP_CLK none


/*
 * jtag_uart_0 configuration
 *
 */

#define ALT_MODULE_CLASS_jtag_uart_0 altera_avalon_jtag_uart
#define JTAG_UART_0_BASE 0x8001080
#define JTAG_UART_0_IRQ 3
#define JTAG_UART_0_IRQ_INTERRUPT_CONTROLLER_ID 0
#define JTAG_UART_0_NAME "/dev/jtag_uart_0"
#define JTAG_UART_0_READ_DEPTH 64
#define JTAG_UART_0_READ_THRESHOLD 8
#define JTAG_UART_0_SPAN 8
#define JTAG_UART_0_TYPE "altera_avalon_jtag_uart"
#define JTAG_UART_0_WRITE_DEPTH 64
#define JTAG_UART_0_WRITE_THRESHOLD 8


/*
 * onchip_memory2_0 configuration
 *
 */

#define ALT_MODULE_CLASS_onchip_memory2_0 altera_avalon_onchip_memory2
#define ONCHIP_MEMORY2_0_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define ONCHIP_MEMORY2_0_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define ONCHIP_MEMORY2_0_BASE 0x0
#define ONCHIP_MEMORY2_0_CONTENTS_INFO ""
#define ONCHIP_MEMORY2_0_DUAL_PORT 0
#define ONCHIP_MEMORY2_0_GUI_RAM_BLOCK_TYPE "AUTO"
#define ONCHIP_MEMORY2_0_INIT_CONTENTS_FILE "soc_d5m_niosii_sys_onchip_memory2_0"
#define ONCHIP_MEMORY2_0_INIT_MEM_CONTENT 0
#define ONCHIP_MEMORY2_0_INSTANCE_ID "NONE"
#define ONCHIP_MEMORY2_0_IRQ -1
#define ONCHIP_MEMORY2_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define ONCHIP_MEMORY2_0_NAME "/dev/onchip_memory2_0"
#define ONCHIP_MEMORY2_0_NON_DEFAULT_INIT_FILE_ENABLED 0
#define ONCHIP_MEMORY2_0_RAM_BLOCK_TYPE "AUTO"
#define ONCHIP_MEMORY2_0_READ_DURING_WRITE_MODE "DONT_CARE"
#define ONCHIP_MEMORY2_0_SINGLE_CLOCK_OP 0
#define ONCHIP_MEMORY2_0_SIZE_MULTIPLE 1
#define ONCHIP_MEMORY2_0_SIZE_VALUE 200096
#define ONCHIP_MEMORY2_0_SPAN 200096
#define ONCHIP_MEMORY2_0_TYPE "altera_avalon_onchip_memory2"
#define ONCHIP_MEMORY2_0_WRITABLE 1


/*
 * sdram_controller_0 configuration
 *
 */

#define ALT_MODULE_CLASS_sdram_controller_0 altera_avalon_new_sdram_controller
#define SDRAM_CONTROLLER_0_BASE 0x4000000
#define SDRAM_CONTROLLER_0_CAS_LATENCY 3
#define SDRAM_CONTROLLER_0_CONTENTS_INFO
#define SDRAM_CONTROLLER_0_INIT_NOP_DELAY 0.0
#define SDRAM_CONTROLLER_0_INIT_REFRESH_COMMANDS 2
#define SDRAM_CONTROLLER_0_IRQ -1
#define SDRAM_CONTROLLER_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SDRAM_CONTROLLER_0_IS_INITIALIZED 1
#define SDRAM_CONTROLLER_0_NAME "/dev/sdram_controller_0"
#define SDRAM_CONTROLLER_0_POWERUP_DELAY 100.0
#define SDRAM_CONTROLLER_0_REFRESH_PERIOD 7.8215
#define SDRAM_CONTROLLER_0_REGISTER_DATA_IN 1
#define SDRAM_CONTROLLER_0_SDRAM_ADDR_WIDTH 0x19
#define SDRAM_CONTROLLER_0_SDRAM_BANK_WIDTH 2
#define SDRAM_CONTROLLER_0_SDRAM_COL_WIDTH 10
#define SDRAM_CONTROLLER_0_SDRAM_DATA_WIDTH 16
#define SDRAM_CONTROLLER_0_SDRAM_NUM_BANKS 4
#define SDRAM_CONTROLLER_0_SDRAM_NUM_CHIPSELECTS 1
#define SDRAM_CONTROLLER_0_SDRAM_ROW_WIDTH 13
#define SDRAM_CONTROLLER_0_SHARED_DATA 0
#define SDRAM_CONTROLLER_0_SIM_MODEL_BASE 0
#define SDRAM_CONTROLLER_0_SPAN 67108864
#define SDRAM_CONTROLLER_0_STARVATION_INDICATOR 0
#define SDRAM_CONTROLLER_0_TRISTATE_BRIDGE_SLAVE ""
#define SDRAM_CONTROLLER_0_TYPE "altera_avalon_new_sdram_controller"
#define SDRAM_CONTROLLER_0_T_AC 4.5
#define SDRAM_CONTROLLER_0_T_MRD 3
#define SDRAM_CONTROLLER_0_T_RCD 15.0
#define SDRAM_CONTROLLER_0_T_RFC 70.0
#define SDRAM_CONTROLLER_0_T_RP 15.0
#define SDRAM_CONTROLLER_0_T_WR 14.0


/*
 * trdb_d5m_0_cmos_sensor_acquisition_0_cmos_sensor_input_0 configuration
 *
 */

#define ALT_MODULE_CLASS_trdb_d5m_0_cmos_sensor_acquisition_0_cmos_sensor_input_0 cmos_sensor_input
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_CMOS_SENSOR_INPUT_0_BASE 0x8001030
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_CMOS_SENSOR_INPUT_0_DEBAYER_ENABLE 1
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_CMOS_SENSOR_INPUT_0_FIFO_DEPTH 32
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_CMOS_SENSOR_INPUT_0_IRQ -1
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_CMOS_SENSOR_INPUT_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_CMOS_SENSOR_INPUT_0_MAX_HEIGHT 1944
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_CMOS_SENSOR_INPUT_0_MAX_WIDTH 2592
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_CMOS_SENSOR_INPUT_0_NAME "/dev/trdb_d5m_0_cmos_sensor_acquisition_0_cmos_sensor_input_0"
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_CMOS_SENSOR_INPUT_0_OUTPUT_WIDTH 32
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_CMOS_SENSOR_INPUT_0_PACKER_ENABLE 0
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_CMOS_SENSOR_INPUT_0_PIX_DEPTH 8
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_CMOS_SENSOR_INPUT_0_SAMPLE_EDGE "FALLING"
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_CMOS_SENSOR_INPUT_0_SPAN 16
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_CMOS_SENSOR_INPUT_0_TYPE "cmos_sensor_input"


/*
 * trdb_d5m_0_cmos_sensor_acquisition_0_msgdma_0_csr configuration
 *
 */

#define ALT_MODULE_CLASS_trdb_d5m_0_cmos_sensor_acquisition_0_msgdma_0_csr altera_msgdma
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_CSR_BASE 0x8001000
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_CSR_BURST_ENABLE 1
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_CSR_BURST_WRAPPING_SUPPORT 0
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_CSR_CHANNEL_ENABLE 0
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_CSR_CHANNEL_ENABLE_DERIVED 0
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_CSR_CHANNEL_WIDTH 8
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_CSR_DATA_FIFO_DEPTH 4096
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_CSR_DATA_WIDTH 64
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_CSR_DESCRIPTOR_FIFO_DEPTH 1024
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_CSR_DMA_MODE 2
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_CSR_ENHANCED_FEATURES 0
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_CSR_ERROR_ENABLE 0
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_CSR_ERROR_ENABLE_DERIVED 0
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_CSR_ERROR_WIDTH 8
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_CSR_IRQ 2
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_CSR_IRQ_INTERRUPT_CONTROLLER_ID 0
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_CSR_MAX_BURST_COUNT 16
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_CSR_MAX_BYTE 8388608
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_CSR_MAX_STRIDE 1
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_CSR_NAME "/dev/trdb_d5m_0_cmos_sensor_acquisition_0_msgdma_0_csr"
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_CSR_PACKET_ENABLE 0
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_CSR_PACKET_ENABLE_DERIVED 0
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_CSR_PREFETCHER_ENABLE 0
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_CSR_PROGRAMMABLE_BURST_ENABLE 0
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_CSR_RESPONSE_PORT 2
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_CSR_SPAN 32
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_CSR_STRIDE_ENABLE 0
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_CSR_STRIDE_ENABLE_DERIVED 0
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_CSR_TRANSFER_TYPE "Aligned Accesses"
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_CSR_TYPE "altera_msgdma"


/*
 * trdb_d5m_0_cmos_sensor_acquisition_0_msgdma_0_descriptor_slave configuration
 *
 */

#define ALT_MODULE_CLASS_trdb_d5m_0_cmos_sensor_acquisition_0_msgdma_0_descriptor_slave altera_msgdma
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_DESCRIPTOR_SLAVE_BASE 0x8001020
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_DESCRIPTOR_SLAVE_BURST_ENABLE 1
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_DESCRIPTOR_SLAVE_BURST_WRAPPING_SUPPORT 0
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_DESCRIPTOR_SLAVE_CHANNEL_ENABLE 0
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_DESCRIPTOR_SLAVE_CHANNEL_ENABLE_DERIVED 0
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_DESCRIPTOR_SLAVE_CHANNEL_WIDTH 8
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_DESCRIPTOR_SLAVE_DATA_FIFO_DEPTH 4096
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_DESCRIPTOR_SLAVE_DATA_WIDTH 64
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_DESCRIPTOR_SLAVE_DESCRIPTOR_FIFO_DEPTH 1024
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_DESCRIPTOR_SLAVE_DMA_MODE 2
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_DESCRIPTOR_SLAVE_ENHANCED_FEATURES 0
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_DESCRIPTOR_SLAVE_ERROR_ENABLE 0
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_DESCRIPTOR_SLAVE_ERROR_ENABLE_DERIVED 0
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_DESCRIPTOR_SLAVE_ERROR_WIDTH 8
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_DESCRIPTOR_SLAVE_IRQ -1
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_DESCRIPTOR_SLAVE_IRQ_INTERRUPT_CONTROLLER_ID -1
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_DESCRIPTOR_SLAVE_MAX_BURST_COUNT 16
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_DESCRIPTOR_SLAVE_MAX_BYTE 8388608
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_DESCRIPTOR_SLAVE_MAX_STRIDE 1
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_DESCRIPTOR_SLAVE_NAME "/dev/trdb_d5m_0_cmos_sensor_acquisition_0_msgdma_0_descriptor_slave"
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_DESCRIPTOR_SLAVE_PACKET_ENABLE 0
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_DESCRIPTOR_SLAVE_PACKET_ENABLE_DERIVED 0
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_DESCRIPTOR_SLAVE_PREFETCHER_ENABLE 0
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_DESCRIPTOR_SLAVE_PROGRAMMABLE_BURST_ENABLE 0
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_DESCRIPTOR_SLAVE_RESPONSE_PORT 2
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_DESCRIPTOR_SLAVE_SPAN 16
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_DESCRIPTOR_SLAVE_STRIDE_ENABLE 0
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_DESCRIPTOR_SLAVE_STRIDE_ENABLE_DERIVED 0
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_DESCRIPTOR_SLAVE_TRANSFER_TYPE "Aligned Accesses"
#define TRDB_D5M_0_CMOS_SENSOR_ACQUISITION_0_MSGDMA_0_DESCRIPTOR_SLAVE_TYPE "altera_msgdma"


/*
 * trdb_d5m_0_i2c_0 configuration
 *
 */

#define ALT_MODULE_CLASS_trdb_d5m_0_i2c_0 i2c
#define TRDB_D5M_0_I2C_0_BASE 0x8001040
#define TRDB_D5M_0_I2C_0_IRQ -1
#define TRDB_D5M_0_I2C_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define TRDB_D5M_0_I2C_0_NAME "/dev/trdb_d5m_0_i2c_0"
#define TRDB_D5M_0_I2C_0_SPAN 4
#define TRDB_D5M_0_I2C_0_TYPE "i2c"


/*
 * trdb_lcm_0_video_pixel_buffer_dma_0 configuration
 *
 */

#define ALT_MODULE_CLASS_trdb_lcm_0_video_pixel_buffer_dma_0 altera_up_avalon_video_pixel_buffer_dma
#define TRDB_LCM_0_VIDEO_PIXEL_BUFFER_DMA_0_BASE 0x40000
#define TRDB_LCM_0_VIDEO_PIXEL_BUFFER_DMA_0_IRQ -1
#define TRDB_LCM_0_VIDEO_PIXEL_BUFFER_DMA_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define TRDB_LCM_0_VIDEO_PIXEL_BUFFER_DMA_0_NAME "/dev/trdb_lcm_0_video_pixel_buffer_dma_0"
#define TRDB_LCM_0_VIDEO_PIXEL_BUFFER_DMA_0_SPAN 16
#define TRDB_LCM_0_VIDEO_PIXEL_BUFFER_DMA_0_TYPE "altera_up_avalon_video_pixel_buffer_dma"


/*
 * trdb_lcm_0_video_rgb_resampler_0 configuration
 *
 */

#define ALT_MODULE_CLASS_trdb_lcm_0_video_rgb_resampler_0 altera_up_avalon_video_rgb_resampler
#define TRDB_LCM_0_VIDEO_RGB_RESAMPLER_0_BASE 0x40010
#define TRDB_LCM_0_VIDEO_RGB_RESAMPLER_0_IRQ -1
#define TRDB_LCM_0_VIDEO_RGB_RESAMPLER_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define TRDB_LCM_0_VIDEO_RGB_RESAMPLER_0_NAME "/dev/trdb_lcm_0_video_rgb_resampler_0"
#define TRDB_LCM_0_VIDEO_RGB_RESAMPLER_0_SPAN 4
#define TRDB_LCM_0_VIDEO_RGB_RESAMPLER_0_TYPE "altera_up_avalon_video_rgb_resampler"

#endif /* __SYSTEM_H_ */
